# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainingapp', '0004_auto_20170724_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
